version: '3.7'

services:
  api:
    container_name: eventos-api
    build: .
    image: eventos-api:dev
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - >-
          ConnectionStrings__eventos=Server=sqlserver;Initial Catalog=eventos;User Id=SA;Password=@eventos1234
    networks:
      - eventos-network
    depends_on:
      - sqlserver

  sqlserver:
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@eventos1234"
      ACCEPT_EULA: "Y"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    networks:
      - eventos-network

networks:
  eventos-network:
    name: eventos-network
    driver: 'bridge'